name: Pipeline Dev CI/CD

on: 
  push:
    branches:
    - main

jobs:
  release:
    name: Build and Push Docker Image
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_DOCKERHUB_NAME }}:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_DOCKERHUB_NAME }}:${{ github.run_number }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'image'
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_DOCKERHUB_NAME }}:latest'
          format: 'sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-docker-results.sarif'
      - name: "Upload Trivy Scan Results"
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: docker-result
          sarif_file: 'trivy-docker-results.sarif'